name: gibbon_music
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^4.0.1
  system_theme: ^2.0.0
  transparent_image: ^2.0.0
  provider: ^6.0.2
  path_provider: ^2.0.10
  fluent_ui: ^4.7.2
  flutter_improved_scrolling: ^0.0.3
  darq: ^1.2.1
  flutter_sticky_header: ^0.6.5
  wave: ^0.2.2
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  flutter_animate: ^4.1.1+1
  bitsdojo_window: ^0.1.5
  device_info_plus: ^8.0.0
  flutter_meedu_videoplayer: any
  image: any
  yam_api:
    path: C:\Users\der-1\StudioProjects\yam_api
  event: any
  async: any
  stack: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
